### ISSUE TITLE
html class 및 attribute 관련해서 고려해주시면 좋을 것 같아요

### ISSUE THREAD

**Issue by SeongjaePark** [artisan91/ssapiano#10]
눌러진 키보드 값에 따라 동적으로 html 태그에 변화가 생겨야 하는 경우 -> data-key="<원하는 키 코드>"

general 건반 -> class="keys"
흰 건반 -> class="keys white_keys" data-key="<원하는 키 코드>"
검은 건반 -> class="keys black_keys" data-key="<원하는 키 코드>"
건반 누르면 아래에 들어갈 효과 -> class="below_keys_effect" data-key="<원하는 키 코드>"

등과 같이 각 HTML 태그의 identity와 그에 적용될 기능에 따라서 클래스 이름을 만들어주시면 javascript에서 해당 태그를 선택하고 사용할 때 보다 편할 것 같습니다.

위의 경우는 단순 예시이므로 영석님과 지윤님 두 분이서 논의해보시고 마음에 드는 클래스 이름 사용해주세요! :)

**Comment by rhyuys115** [comment]
건반 하나를 의미하는 영역은 class="key" 로 추가하면 어떨까요? css 추가로 작성 안하고 기존 건반 영역 class에 key를 추가해주시면 됩니다!

**Comment by Helia-17** [comment]
오호 확인했습니다

**Comment by ojin0611** [comment]
잘 반영됐네요!!
