### ISSUE TITLE
영석님 RYS 브랜치 main으로 머지 가능하실까요?

### ISSUE THREAD

**Issue by SeongjaePark** [artisan91/ssapiano#12]

**Comment by rhyuys115** [comment]
index.html에서 소리나게 수정해서 push해놨습니다!

**Comment by ojin0611** [comment]
conflict 없으면 merge도 직접 한번 해주세요!! ㅎㅎ

**Comment by rhyuys115** [comment]
로컬에서 merge 해보고 conflict 없어서 main으로 push했습니다!

**Comment by ojin0611** [comment]
감사합니다. issue closed 부탁드려용
