### ISSUE TITLE
피아노 건반 배치 제안

### ISSUE THREAD

**Issue by ojin0611** [artisan91/ssapiano#13]
실제 키보드 배치와 유사한 건반 배치를 하는게 사용자 편의에 좋을것같습니다.

우선 실제 키보드 아래에서 입력하는 것이 화면의 상단에 표시되는 것을 서로 바꿨으면 좋겠습니다.

두번째로, 아랫줄은 왼쪽 shift부터 오른쪽 shift까지, 윗줄은 tab부터 ]까지 입력할 수 있었으면 좋겠습니다.

두 개의 건반이 같은 소리를 내는 경우는 아래처럼 제작하면 가능할 것으로 보입니다.
1. data-key는 다르게, data-code는 같은 2개의 태그를 생성한다.
2. css로 같은 위치에 겹쳐지도록 표시한다.
3. 연주중인 key의 클래스(active_key)에 해당하는 css에 z-index를 설정해준다. 그럼 두 건반이 겹쳐져도 연주중인 경우 상단에 표시된다.

**Comment by rhyuys115** [comment]
확인했습니다. 저 안으로 진행해보겠습니다.

**Comment by Helia-17** [comment]
오 좋은 것 같아요! 그렇게 만들어볼게요

**Comment by ojin0611** [comment]
shift tab 제거하고 건반 배치 확인했습니다~
