### ISSUE TITLE
옥타브 업 다운 키는 어떤 키로 설정하면 좋을까요?

### ISSUE THREAD

**Issue by SeongjaePark** [artisan91/ssapiano#14]

**Comment by rhyuys115** [comment]
직관성을 생각하면 왼쪽 ctrl(down) 오른쪽 ctrl(up)이 좋을 것 같긴 합니다

**Comment by ojin0611** [comment]
ctrl 키가 1개인 컴퓨터도 가끔 있어서.. 방향키도 괜찮을거같아요. 맥북은 ctrl이랑 alt, 여기 다르지않나요글구??

**Comment by SeongjaePark** [comment]
@ojin0611 오 방향키 괜찮은 것 같네요! 
맞아요 맥북에서는 키 명칭들과 역할이 윈도우와 좀 다르더라구요. 그건 공부해서 적용하면 되긴 하지만, 지금은 방향키가 더 적절한 것 같습니당 고마워요!
