### ISSUE TITLE
refactor event.keyCode -> event.key

### ISSUE THREAD

**Issue by SeongjaePark** [artisan91/ssapiano#15]
MDN 문서를 보니 keyboardEvent 객체의 keyCode 프로퍼티가 deprecated 되었고 event.key 프로퍼티를 대신 사용하기를 권장하고 있습니다.
따라서 sound.js 파일과 여타 html 파일에서 관련 부분들을 수정하도록 하겠습니다. data-key 속성의 값이 변경되오니 참고해주세요

**Comment by SeongjaePark** [comment]
방금 index.html 코드를 수정하다보니, 소리는 다시 맞게 작동하는데, css와 연관된 부분이 있는지 검은 건반이 사라지는데, 혹시 나중에 이 부분 살펴봐주실 수 있을까요? @rhyuys115

**Comment by SeongjaePark** [comment]
다른 부분은 키는 잘 작동하는데, 아무래도 백슬래쉬('\')는 기존 방식대로 동작을 안 하고, '\\\\' 이런 식으로 네 개를 써야 인식이 되네요;
https://stackoverflow.com/questions/22830519/what-chars-needs-escaping-in-queryselector 이 곳을 참고하니 아무래도 여러 번 이스케이핑해야 되는 상황이 발생해서; 그런 것 같아요
sound.js 파일 내에서 이 부분만 if 문 사용해서 수정해주도록 하겠습니다~

**Comment by Helia-17** [comment]
확인했습니다!

**Comment by ojin0611** [comment]
이거 논의 끝난거면 close해주세요~
