### ISSUE TITLE
옥타브 기능 프로토타입 확인 바랍니다

### ISSUE THREAD

**Issue by SeongjaePark** [artisan91/ssapiano#16]
옥타브 조절 기능 프로토타입 만들어서 feature/octave_set 브랜치에 커밋했습니다~
위, 아래 방향 키로 조정 가능하고, 이미 옥타브가 0이거나 7일 경우 무시되도록 했습니다.

추가로, 사용자에게 한 번에 제공되는 옥타브의 범위에 따라서 sound.js 파일 수정이 필요할 것 같은데 이 부분 다시 한 번 이야기해볼 수 있으면 좋을 것 같아요

**Comment by rhyuys115** [comment]
확인해본 결과 위, 아래 방향키로 설정하니 화면이 이동하는 문제점이 있습니다. 좌,우 방향키로 설정하는 것이 더 좋을 것 같습니다.

**Comment by Helia-17** [comment]
오 이제 feature별 브랜치도 생겼군요

**Comment by SeongjaePark** [comment]
@rhyuys115 확인하여 브랜치에 반영했습니다.

**Comment by ojin0611** [comment]
이거 옥타브기능 프로토타입 제작 완료되면, 실연주 시연 부탁드려요!!

**Comment by ojin0611** [comment]
확인 완료 ㅎㅎ 작동 잘됩니다~ close ㄱㄱ
