### ISSUE TITLE
Tab키를 여러 번 누르면 keydown 상태로 유지됩니다.

### ISSUE THREAD

**Issue by rhyuys115** [artisan91/ssapiano#17]

**Comment by rhyuys115** [comment]
2줄로 사용할 건반들을 모두 추가하였는데 tab키를 3번 이상 누르면 키가 올라와도 소리가 계속 나는 현상이 나타납니다.(현재 layout/piano 브랜치에 올렸습니다.) 추가적으로 오른쪽 shift도 예외처리가 필요해보입니다.

**Comment by SeongjaePark** [comment]
@rhyuys115 tab 키의 브라우저 상 기본동작 때문이 발생하는 오류인 것 같습니다. 현재 키 구조 변경에 대해 논의 중이고, tab 사용여부에 대해서도 논의 중입니다.

**Comment by ojin0611** [comment]
tab 삭제하고 shift r 삭제했어요~
