### ISSUE TITLE
README.md 작성

### ISSUE THREAD

**Issue by ojin0611** [artisan91/ssapiano#18]
readme 라는 branch 따겠습니다.
`readme` 브랜치를 각자 pull해서, README.md 작성하고, 다시 `readme` branch에 push해주세요.

어떤 내용 적을지는 여기 댓글로 남겨볼까요!!

(참여하시고싶은분은 Assignees에 assign yourself 눌러주세요)

**Comment by ojin0611** [comment]
는 이미 성재가 branch를 만들어놨네

**Comment by SeongjaePark** [comment]
@ojin0611 저는 readme branch를 만든 적이 없습니다?..😅

**Comment by ojin0611** [comment]
내가 readme 브랜치 따서 아무것도 commit 안한상태로 push했더니, 최근에 main을 수정한게 성재여서 그렇게 떴던거임ㅎㅎ 다시올리겠음
