### ISSUE TITLE
같은 음을 내는 건반이 여러개일때 발생하는 문제

### ISSUE THREAD

**Issue by ojin0611** [artisan91/ssapiano#19]
초기에 피아노를 설계할때는 각 음을 내는 건반이 딱 1개씩만 존재했습니다.
그래서 컴퓨터 키보드의 keyCode (현재는 key)로만 현재 연주중인지 아닌지를 판단하는 코드를 작성했었습니다.

그런데 개선된 피아노에서는 하나의 음을 내는 건반이 2개 이상 존재하는 경우가 발생합니다.
1. / = tab
2. shift+r = q

위의 경우를 대비해서 현재 연주중인지 아닌지 keyCode가 아닌 연주중인 음의 코드로 판별할 수 있도록 코드 수정이 필요해보입니다.

**Comment by ojin0611** [comment]
아니면 tab이랑 shift를 날려버리는게 깔끔할수도있겠네요

**Comment by SeongjaePark** [comment]
@ojin0611 네 어제 HTML 태그 논의가 필요하다고 한 게 그 부분입니다.

**Comment by ojin0611** [comment]
전 날리는거 좋아요

**Comment by ojin0611** [comment]
tab 삭제하고 shift r 삭제했어요~
