### ISSUE TITLE
브라우저의 키 입력 vs 싸피아노 키입력

### ISSUE THREAD

**Issue by ojin0611** [artisan91/ssapiano#31]
브라우저(또는 html) 내장기능과 충돌하는 몇가지 키 입력을 해결하고자한다.

1. Space (페이지 아래로 이동 vs Pedal)
2. F1 (support google vs Documentation)
3. S,T (sound type 선택 직후 s또는t 입력시 해당 알파벳으로 시작하는 항목 선택 vs 그냥 연주)
4. Tab (화면 내 이동 vs 잘못입력된 값)

**Comment by SeongjaePark** [comment]
@ojin0611 제가 한 번 해결해보겠습니다~

**Comment by SeongjaePark** [comment]
@ojin0611

아래와 같이 진행했습니다.
1. Space 키 페이지 아래 이동 기능 비활성화
2. F1 키 - 보류
3. 현재 상태(전자) 괜찮은 것 같아서 변경X
4. window 객체에서 Tab 키 기본 기능 비활성화

**Comment by ojin0611** [comment]
f1은 그냥 필수기능이 아니므로 pass
