### ISSUE TITLE
메트로놈 제작하기

### ISSUE THREAD

**Issue by ojin0611** [artisan91/ssapiano#32]
박자에 맞게 연주할 수 있도록 도와주는 메트로놈을 두고싶어요.

자유로운 의견 남겨봐요!

**Comment by rhyuys115** [comment]
andante moderato 같은 기준으로 작동되게 심플하게 일단 만들어보겠습니다.

**Comment by rhyuys115** [comment]
일단 bpm 바로 조절해서 버튼 누르면 시작하고 다시 누르면 정지하는 형태로 원본 파일과 분리해서 만들었습니다. 재생, 정지에 따라 버튼 아이콘 변경, 비트마다 다른 음원 재생을 통해 더 박자감있게 하는 기능 추가 구현 예정입니다.

**Comment by SeongjaePark** [comment]
@rhyuys115 오 신기하네요~ 고생하셨습니다!

근데 올려주신 브랜치에서 테스트해보니, 메트로놈 플레이 버튼 최초 클릭 시에 작동을 안 하고 오히려 정지 버튼을 누르면 작동하더라고요. 이 부분 확인 부탁드릴게요!

**Comment by SeongjaePark** [comment]
@rhyuys115 메트로놈 속도 조절을 슬라이드 바 대신에 몇 가지 bpm 또는 박자 선택지를 주는 것도 좋을 것 같습니다!

**Comment by ojin0611** [comment]
영석님이 새로 만든 issue가 있으므로 close
