### ISSUE TITLE
Hint 띄우기

### ISSUE THREAD

**Issue by Helia-17** [artisan91/ssapiano#6]
ojin0611 commented 13 hours ago

C3, D3, G#4 등 음을 띄우는 방법도 있고,
어떤 키를 입력해야되는지 띄우는 방법도 있다.

클릭도 인식하게 하는 것을 감안하면, 음을 띄우는 것도 좋을 듯!
옥타브 변환을 감안해도 (바뀐) 음을 표시하는 것이 좋을듯!

결론은, 유저가 선택함에 따라 어떤 내용을 hint로 띄울지 바꿀 수 있는 기능이 필요하다.

**Comment by ojin0611** [comment]
시작할때 assign yourself 클릭하고 말해주세요~~

**Comment by ojin0611** [comment]
일단은 키보드 입력만 띄웠어요.
