### ISSUE TITLE
피아노 디자인

### ISSUE THREAD

**Issue by rhyuys115** [artisan91/ssapiano#7]
건반은 4줄에 걸쳐서 2옥타브
pianokeyboard

한 화면에 표시할 건반 수는 나중에 정하고, 일단 모든 건반을 html로 제작. 필요에 따라 일부만 보여주기
디자인은 @Helia-17 , @rhyuys115 님이 담당!!
소리는 @SeongjaePark , @ojin0611 님이 담당!!

**Comment by Helia-17** [comment]
저는 길게 2줄로 하려고 하는데 상관없겠죠? 사실 1줄이 제일 하고싶긴합니다

**Comment by rhyuys115** [comment]
반응형으로 큰화면일때는 1줄 줄어들면 2줄 되는건 어떠신가요..!?!?

**Comment by ojin0611** [comment]
반응형도 좋은 생각이네요! 단순히 사용자가 직접 선택하는 옵션이 아니라, 강제로 변경하는 방법도 괜찮은것같아요.

**Comment by ojin0611** [comment]
직접 선택할 수 있게 제작했어요.
